import { useState, type FormEvent } from 'react';
import { apiJson, apiRequest } from '../lib/api';
import type { MatchImportResult, MatchImportReviewData } from '../lib/types';
import { MatchImportReview } from './MatchImportReview';
import { ImportQualitySummary } from './ImportQualitySummary';

export function MatchImportDrawer({onComplete}:{onComplete:()=>Promise<void>|void}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const[review,setReview]=useState<MatchImportReviewData|null>(null),[qualityResult,setQualityResult]=useState<MatchImportResult|null>(null);
 function acceptResult(result:MatchImportResult){
   if(result.status==='needs_review'&&result.review){setReview(result.review);setQualityResult(null);setMessage('');return false;}
   setReview(null);setQualityResult(result.status==='enriched'&&result.quality?result:null);setMessage(describe(result));return true;
 }
 async function urlSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const sourceUrl=String(new FormData(e.currentTarget).get('sourceUrl')||'');const d=await apiJson<{result:MatchImportResult}>('match-import-url',{sourceUrl});if(acceptResult(d.result))await onComplete();}catch(error){setMessage(error instanceof Error?error.message:'Import failed.');}finally{setBusy(false);}}
 async function fileSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const fd=new FormData(e.currentTarget);const d=await apiRequest<{results:Array<MatchImportResult&{file:string;status:string}>}>('match-import-file',{method:'POST',body:fd});const needsReview=d.results.find(x=>x.status==='needs_review'&&x.review);if(needsReview){acceptResult(needsReview as MatchImportResult);return;}const enriched=d.results.find(x=>x.status==='enriched'&&x.quality);if(enriched)acceptResult(enriched as MatchImportResult);else setMessage(`${d.results.length} file${d.results.length===1?'':'s'} processed • ${d.results.filter(x=>x.status==='enriched').length} enriched • ${d.results.filter(x=>x.status==='needs_review').length} need review`);await onComplete();}catch(error){setMessage(error instanceof Error?error.message:'Import failed.');}finally{setBusy(false);}}
 async function resolveReview(action:'confirm'|'choose_existing'|'create_missing',matchId?:string){if(!review)return;setBusy(true);try{const d=await apiJson<{result:MatchImportResult}>('match-import-review',{sourceArtifactId:review.sourceArtifactId,action,...(matchId?{matchId}:{})});acceptResult(d.result);await onComplete();}catch(error){setMessage(error instanceof Error?error.message:'Match review failed.');}finally{setBusy(false);}}
 function describe(r:MatchImportResult){if(!r)return'Import complete.';if(r.status==='enriched')return`Match enriched • ${r.observationCount??0} evidence observations • ${r.analytics?.metricCount??0} metrics recalculated`;if(r.status==='duplicate')return'Already available — this exact source was previously imported.';return`Source preserved • ${r.observationCount??0} observations • review needed to identify the match.`;}
 function close(){if(busy)return;setOpen(false);setReview(null);setQualityResult(null);setMessage('');}
 return <><button className="primary-button" onClick={()=>setOpen(true)}>+ Add Match Data</button>{open&&<div className="modal-backdrop" onClick={close}><section className="import-modal" onClick={e=>e.stopPropagation()}><header><div><span className="eyebrow">Evidence ingestion</span><h2>Add Match Data</h2></div><button className="icon-button" onClick={close} aria-label="Close">×</button></header>{review?<MatchImportReview review={review} busy={busy} onResolve={resolveReview}/>:qualityResult?.quality?<ImportQualitySummary quality={qualityResult.quality} matchId={qualityResult.matchId}/>:<><p className="muted">Use whatever data you have. Better data makes the answer deeper.</p><form className="import-block" onSubmit={urlSubmit}><label>Paste public box-score URL</label><div className="input-action"><input name="sourceUrl" type="url" placeholder="https://school.edu/.../boxscore/..." required/><button disabled={busy}>Import URL</button></div></form><div className="or-line"><span>or</span></div><form className="import-block" onSubmit={fileSubmit}><label>Upload official XML / VolleyMetrics evidence</label><input name="files" type="file" multiple accept=".xml,.html,.htm,.txt,.json" required/><button className="secondary-button" disabled={busy}>Process Files</button></form></>}{message&&<div className="import-result">{message}</div>}</section></div>}</>;
}
