import { useState, type FormEvent } from 'react';
import { apiJson, apiRequest } from '../lib/api';
export function MatchImportDrawer({onComplete}:{onComplete:()=>Promise<void>|void}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function urlSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const sourceUrl=String(new FormData(e.currentTarget).get('sourceUrl')||'');const d=await apiJson<any>('match-import-url',{sourceUrl});setMessage(describe(d.result));await onComplete();}catch(error){setMessage(error instanceof Error?error.message:'Import failed.');}finally{setBusy(false);}}
 async function fileSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const fd=new FormData(e.currentTarget);const d=await apiRequest<any>('match-import-file',{method:'POST',body:fd});setMessage(`${d.results.length} file${d.results.length===1?'':'s'} processed • ${d.results.filter((x:any)=>x.status==='enriched').length} enriched • ${d.results.filter((x:any)=>x.status==='needs_review').length} need review`);await onComplete();}catch(error){setMessage(error instanceof Error?error.message:'Import failed.');}finally{setBusy(false);}}
 function describe(r:any){if(!r)return'Import complete.';if(r.status==='enriched')return`Match enriched • ${r.observationCount} evidence observations • ${r.analytics?.metricCount??0} metrics recalculated`;if(r.status==='duplicate')return'Already available — this exact source was previously imported.';return`Source preserved • ${r.observationCount??0} observations • review needed to identify the match.`;}
 return <><button className="primary-button" onClick={()=>setOpen(true)}>+ Add Match Data</button>{open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><section className="import-modal" onClick={e=>e.stopPropagation()}><header><div><span className="eyebrow">Evidence ingestion</span><h2>Add Match Data</h2></div><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close">×</button></header><p className="muted">Use whatever data you have. Better data makes the answer deeper.</p><form className="import-block" onSubmit={urlSubmit}><label>Paste public box-score URL</label><div className="input-action"><input name="sourceUrl" type="url" placeholder="https://school.edu/.../boxscore/..." required/><button disabled={busy}>Import URL</button></div></form><div className="or-line"><span>or</span></div><form className="import-block" onSubmit={fileSubmit}><label>Upload official XML / VolleyMetrics evidence</label><input name="files" type="file" multiple accept=".xml,.html,.htm,.txt,.json" required/><button className="secondary-button" disabled={busy}>Process Files</button></form>{message&&<div className="import-result">{message}</div>}</section></div>}</>;
}
